mysql:

  namespace: mysql

  secrets:
    data:
      MYSQL_ROOT_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
      MYSQL_USER: "YXBwX3VzZXI=" # Base64 encoding for "app_user"
      MYSQL_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"

  image:
    name: mysql
    repository: mysql
    version: "8.0"

  replicas: 2

  resources:
    requests:
      cpu: 500m
      memory: 1Gi

  volumeClaimTemplates:
    resources:
      requests:
        storage: 2Gi

  affinity:
    podAffinity:
      key: "app"
      value: "mysql"
    nodeAffinity:
      key: "app"
      value: "mysql"
