todoapp:

  namespace: todoapp

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  secrets:
    data:
      SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
      DB_NAME: "YXBwX2RiCg=="
      DB_USER: "YXBwX3VzZXI="
      DB_PASSWORD: "MTIzNA=="
      DB_HOST: "bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbAo="

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  image:
    name: todoapp
    repository: dariasavchenko/todoapp
    version: 5.0.1

  affinity:
    nodeAffinity:
      key: app
      values:
        - todoapp

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      averageUtilization: 70
    memory:
      averageUtilization: 70

  pv:
    capacity:
      storage: 2Gi

  pvc:
    requests:
      storage: 1Gi

  serviceAccount:
    name: secrets-reader

  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
      app: prometheus
    interval: 10s
    path: /metrics
    port: http
    namespace: default

