apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nodeport
  namespace: {{ .Values.todoapp.namespace }}
  labels:
    app: { .Chart.Name }}
    job: { .Chart.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007

